### ISSUE TITLE
set kaldi root directory

### ISSUE THREAD

**Issue by gauravgund** [wangyu09/exkaldi#17]
Hi,

I have installed kaldi and exkaldi both. when i am running the following command:

! python3 -c "import exkaldi"

**I am getting the following error**:

Warning: Kaldi root directory was not found in system PATH. You can appoint it:
exkaldi.info.reset_kaldi_root( yourPath )
If not, ERROR will occur when implementing some core functions.

**How to handle this? I am getting KaldiProcessError: Failed to generate L.fst.**

**Comment by luvwinnie** [comment]
@gauravgund Hi, did you set your kaldi directory for KALDI_ROOT or PATH? you need to be able use the kaldi command.

**Comment by gauravgund** [comment]
Hi, 
I am doing it on colab. I did something like this:

exkaldi.info.reset_kaldi_root('/content/content/kaldi')

as given by warning! Is there any other way to do this? But I am still getting the warning!

**Comment by luvwinnie** [comment]
yes you can just set with the reset_kaldi_root

**Comment by gauravgund** [comment]
But i am still getting the warning:
Warning: Kaldi root directory was not found in system PATH. You can appoint it:
exkaldi.info.reset_kaldi_root( yourPath )
If not, ERROR will occur when implementing some core functions.

**Comment by luvwinnie** [comment]
May I know how did you setup the colab? Can you share the notebook So I can take a look?

**Comment by gauravgund** [comment]
Here it is:

https://github.com/gauravgund/gauravgund/blob/master/Exkaldi.ipynb

**Comment by luvwinnie** [comment]
Did you compile the kaldi within the colab?

**Comment by gauravgund** [comment]
Yes, installed Kaldi based on :
http://jrmeyer.github.io/asr/2016/01/26/Installing-Kaldi.html

Zip the Kaldi format and unzipping it in the notebook

**Comment by luvwinnie** [comment]
Could you try to add these line? Sorry that we didn't test in colab. I think it need to add the kaldi's bin file to the PATH environment variable.
```
%env KALDI_ROOT=/content/content/kaldi
```

```
import os
import glob
for bin_path in glob.glob("/content/content/kaldi/src/*bin"):
  os.environ["PATH"] += ":"+bin_path
# Add bin path to PATH in order to use kaldi command.
import exkaldi
```

**Comment by gauravgund** [comment]
That warning vanished but when i am running the following command:

Lfile = '/content/kaldi_exp/exp/L.fst'
exkaldi.decode.graph.make_L(lexicons, outFile=Lfile, useDisambigLexicon=False)

**Error:**

fstarcsort: error while loading shared libraries: libfstscript.so.10: cannot open shared object file: No such file or directory
fstcompile: error while loading shared libraries: libfstscript.so.10: cannot open shared object file: No such file or directory

---------------------------------------------------------------------------
KaldiProcessError                         Traceback (most recent call last)
<ipython-input-38-4499db09ca49> in <module>()
      1 Lfile = '/content/kaldi_exp/exp/L.fst'
----> 2 exkaldi.decode.graph.make_L(lexicons, outFile=Lfile, useDisambigLexicon=False)

/usr/local/lib/python3.7/dist-packages/exkaldi/decode/graph.py in make_L(lexicons, outFile, useSilprobLexicon, useSilprob, useDisambigLexicon)
   1532                                 raise KaldiProcessError("Failed to generate L_disambig.fst.")
   1533                         else:
-> 1534                                 raise KaldiProcessError("Failed to generate L.fst.")
   1535                 else:
   1536                         return os.path.abspath(outFile)

KaldiProcessError: Failed to generate L.fst.

**Comment by luvwinnie** [comment]
Are you really compile with the Colab Environment? The kaldi normally can only be used in the compiled(installed)  environment. You can reference this [issue](https://github.com/kaldi-asr/kaldi/issues/3009)

**Comment by gauravgund** [comment]
I am able to solve it by converting /content/content/kaldi to /content/kaldi. Thanks for your help! :)
