### ISSUE TITLE
Kaldi root directory was not found in system PATH

### ISSUE THREAD

**Issue by askinucuncu** [wangyu09/exkaldi#7]
Hello. The system Kaldi-asr installed. I also installed ExKaldi. However I am getting the following error. Can you help me?

python3 -c "import exkaldi"
Warning: Kaldi root directory was not found in system PATH. You can appoint it:
exkaldi.info.reset_kaldi_root( yourPath )
If not, ERROR will occur when implementing some core functions.

**Comment by wangyu09** [comment]
Hello. Can you show me the PATHs of your environment?

**Comment by askinucuncu** [comment]
Kaldi Root Path;
/home/bcode/kaldi

**Comment by wangyu09** [comment]
sorry, I meant you check the system environments by running shell command "export -p | grep PATH". Maybe the Kaldi root directory has not been appended to the "PATH" so that the ExKaldi could not detect it.

**Comment by askinucuncu** [comment]
Soryy,

declare -x PATH="**/home/bcode/kaldi:**/usr/local/cuda-10.0/bin:/usr/local/cuda-10.0/bin:/usr/local/cuda-10.0/bin:/usr/local/cuda-10.0/bin:/home/bcode/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin"
declare -x WINDOWPATH="1"

**Comment by askinucuncu** [comment]
declare -x KALDI_ROOT="/home/bcode/kaldi"

**Comment by askinucuncu** [comment]
> Soryy,
> 
> declare -x PATH="**/home/bcode/kaldi:**/usr/local/cuda-10.0/bin:/usr/local/cuda-10.0/bin:/usr/local/cuda-10.0/bin:/usr/local/cuda-10.0/bin:/home/bcode/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin"
> declare -x WINDOWPATH="1"

declare -x KALDI_ROOT="/home/bcode/kaldi"

**Comment by wangyu09** [comment]
We hope not only the "/home/bcode/kaldi" has existed in PATH but also the related "/home/bcode/kaldi/tools/openfst", "/home/bcode/kaldi/src/featbin", "/home/bcode/kaldi/src/Gambian", "/home/bcode/kaldi/src/bin" and "/home/bcode/kaldi/src/nnetbin" have been appended to the PATH successfully in your case when you installed the Kaldi. We also provided an another way: at every time you import the exkaldi, you can assign the kaldi root directory manually, like this:
`import exkaldi
exkaldi.info.reset_kaldi_root("/home/bcode/kaldi")
`
This operation will add all the directories above to the ExKaldi running environment. After done this, you can check the PATHs by running:
`
print(exkaldi.info.ENV["PATH"])
`
Can you try it?

**Comment by askinucuncu** [comment]
Problem solved. Thank you for your help
