### ISSUE TITLE
02_feature_processing.ipynb 

### ISSUE THREAD

**Issue by askinucuncu** [wangyu09/exkaldi#8]
Hello. In Tutorials 2 I get an error in the section below. What's wrong? All previous steps have been successful.

--------------------------------------------------------------------------

spk2uttFile = os.path.join(dataDir, "train", "spk2utt")
cmvn = exkaldi.compute_cmvn_stats(feat, spk2utt=spk2uttFile, name="cmvn")
cmvn

---------------------------------------------------------------------------
⌄⌄⌄⌄⌄⌄⌄⌄⌄⌄⌄⌄⌄⌄⌄⌄⌄⌄⌄⌄⌄⌄⌄⌄⌄⌄⌄⌄⌄⌄

KaldiProcessError                         Traceback (most recent call last)
<ipython-input-29-73e445785e87> in <module>
      1 spk2uttFile = os.path.join(dataDir, "train", "spk2utt")
      2 
----> 3 cmvn = exkaldi.compute_cmvn_stats(feat, spk2utt=spk2uttFile, name="cmvn")
      4 
      5 cmvn

/usr/local/lib/python3.6/dist-packages/exkaldi/core/feature.py in compute_cmvn_stats(feat, spk2utt, name, outFile)
    489                 resources  = {"feat":feats,"spk2utt":spk2utts,"outFile":outFiles}
    490 
--> 491         return run_kaldi_commands_parallel(resources,cmdPattern,analyzeResult=True,generateArchive="cmvn",archiveNames=names)
    492 
    493 def use_cmvn_sliding(feat,windowSize=None,std=False):

/usr/local/lib/python3.6/dist-packages/exkaldi/core/common.py in run_kaldi_commands_parallel(resources, cmdPattern, analyzeResult, timeout, generateArchive, archiveNames)
    403                                 if cod != 0:
    404                                         finalCmd = ",".join([cmd.strip().split(maxsplit=1)[0] for cmd in finalCmd.split("|")])
--> 405                                         raise KaldiProcessError(f"Failed to run Kaldi command: {finalCmd}.",err.decode())
    406 
    407                         if outFile == "-":

KaldiProcessError: Failed to run Kaldi command: compute-cmvn-stats.
compute-cmvn-stats --spk2utt=ark:librispeech_dummy_tr/train/spk2utt ark:- ark:- 
WARNING (compute-cmvn-stats[5.5.825~1-5426a6]:main():compute-cmvn-stats.cc:107) Did not find features for utterance common_voice_tr_21577593-000000-000420
WARNING (compute-cmvn-stats[5.5.825~1-5426a6]:main():compute-cmvn-stats.cc:123) No stats accumulated for speaker s5
WARNING (compute-cmvn-stats[5.5.825~1-5426a6]:main():compute-cmvn-stats.cc:107) Did not find features for utterance common_voice_tr_21577558-000000-000451
WARNING (compute-cmvn-stats[5.5.825~1-5426a6]:main():compute-cmvn-stats.cc:123) No stats accumulated for speaker s3
WARNING (compute-cmvn-stats[5.5.825~1-5426a6]:main():compute-cmvn-stats.cc:107) Did not find features for utterance common_voice_tr_21577594-000000-000451
WARNING (compute-cmvn-stats[5.5.825~1-5426a6]:main():compute-cmvn-stats.cc:123) No stats accumulated for speaker s6
WARNING (compute-cmvn-stats[5.5.825~1-5426a6]:main():compute-cmvn-stats.cc:107) Did not find features for utterance common_voice_tr_21577595-000000-000417
WARNING (compute-cmvn-stats[5.5.825~1-5426a6]:main():compute-cmvn-stats.cc:123) No stats accumulated for speaker s7
WARNING (compute-cmvn-stats[5.5.825~1-5426a6]:main():compute-cmvn-stats.cc:107) Did not find features for utterance common_voice_tr_21577557-000000-000426
WARNING (compute-cmvn-stats[5.5.825~1-5426a6]:main():compute-cmvn-stats.cc:123) No stats accumulated for speaker s2
WARNING (compute-cmvn-stats[5.5.825~1-5426a6]:main():compute-cmvn-stats.cc:107) Did not find features for utterance common_voice_tr_21577555-000000-000364
WARNING (compute-cmvn-stats[5.5.825~1-5426a6]:main():compute-cmvn-stats.cc:123) No stats accumulated for speaker s1
WARNING (compute-cmvn-stats[5.5.825~1-5426a6]:main():compute-cmvn-stats.cc:107) Did not find features for utterance common_voice_tr_21596661-000000-000379
WARNING (compute-cmvn-stats[5.5.825~1-5426a6]:main():compute-cmvn-stats.cc:123) No stats accumulated for speaker s8
WARNING (compute-cmvn-stats[5.5.825~1-5426a6]:main():compute-cmvn-stats.cc:107) Did not find features for utterance common_voice_tr_21596663-000000-000412
WARNING (compute-cmvn-stats[5.5.825~1-5426a6]:main():compute-cmvn-stats.cc:123) No stats accumulated for speaker s9
WARNING (compute-cmvn-stats[5.5.825~1-5426a6]:main():compute-cmvn-stats.cc:107) Did not find features for utterance common_voice_tr_21577592-000000-000513
WARNING (compute-cmvn-stats[5.5.825~1-5426a6]:main():compute-cmvn-stats.cc:123) No stats accumulated for speaker s4
LOG (compute-cmvn-stats[5.5.825~1-5426a6]:main():compute-cmvn-stats.cc:171) Done accumulating CMVN stats for 0 utterances; 9 had errors.

**Comment by wangyu09** [comment]
Hello. This error comes from Kaldi backend. It means that your utterance IDs in feature object did not match these IDs defined in you spk2utt file. I guess you might have replaced some tutorial resource files. Can you show me the utterance IDs info in feature? You can run this command `print(feat.utts[0])` . And also show me the top 1 line of your spk2utt file please.

**Comment by wangyu09** [comment]
Close due to the inactivity
